---
- hosts:  all,!localhost
  tags:   always
  pre_tasks:
  - setup:

- hosts:  all
  tags:   basic-setup
  roles: [basic_setup]

- hosts:  db
  tags:   postgres-setup
  roles: [postgres_setup]
  vars:
    allowed_clients: "{{ groups.app }}"

- hosts: db
  tags: create-db
  become: yes
  become_user: postgres
  vars_files: ["{{ deploy_vars_file }}"]
  tasks:
  - postgresql_user: name={{ db_user }} password={{ db_pass }}
  - postgresql_db:   name={{ db_name }} owner={{ db_user }}

- hosts:  app
  tags:   deploy-user
  roles: [deploy_user]
  vars_files: ["{{ deploy_vars_file }}"]
  vars:
    username: "{{ deploy_user      }}"
    password: "{{ deploy_user_pass }}"

- hosts: localhost
  connection: local
  tags: build-frontend
  vars_files: ["{{ deploy_vars_file }}"]
  roles: [build_frontend]

- hosts: app
  vars_files: ["{{ deploy_vars_file }}"]
  roles:
    - { role: nginx_setup,     tags: nginx-setup     }
    - { role: python_setup,    tags: python-setup    }
    - { role: deploy_backend,  tags: deploy-backend  }
    - { role: deploy_frontend, tags: deploy-frontend }
    - { role: deploy_nginx,    tags: deploy-nginx    }

- hosts: localhost
  connection: local
  tags: build-frontend
  vars_files: ["{{ deploy_vars_file }}"]
  roles: [clean_after_build_frontend]
