---
- hosts: all
  become: yes
  pre_tasks:
  - apt: update_cache=yes cache_valid_time=3600

  tasks:
  - apt: name=tree,htop state=present

  - apt:     name=ntp state=present
  - service: name=ntp state=started enabled=yes

  - ufw: state=enabled
  - ufw: rule=allow port=22 proto=tcp

  - user: >
      name=alto groups=sudo shell=/bin/bash
      password={{ 'alto' | password_hash('sha512') }} update_password=on_create


- hosts: app
  become: yes
  become_user: alto
  tasks:
  - file: path=~/.ssh state=directory mode=700
  - copy: src=keys/ansible_testing     dest=~/.ssh/ mode=600
  - copy: src=keys/ansible_testing.pub dest=~/.ssh/ mode=644
  - blockinfile:
      dest: ~/.ssh/config
      create: yes
      block: |
        Host gitlab.alto-apps.mine.nu
          IdentityFile ~/.ssh/ansible_testing
  - known_hosts: >
      host=gitlab.alto-apps.mine.nu
      key="|1|mFo7fs8KMgu0G53K9sagnGkgu7s=|GMg2NKCg8tyg/DVBFmkrMQDjTh4= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpqCp4+FXQOvXeoxclHD3ejSY6Wr4knvDmFWCnOq5e1"

  - file:    path=~/.local/bin state=directory
  - get_url: url=https://pyenv.run dest=~/.local/bin/install_pyenv.sh mode=744
  - command: ~/.local/bin/install_pyenv.sh
      creates=~/.pyenv
  - blockinfile:
      dest: ~/.bashrc
      insertbefore: "If not running interactively, don't do anything"
      block: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
  - apt: name=build-essential,libssl-dev,zlib1g-dev,libbz2-dev,libreadline-dev,libffi-dev state=present
    become: yes
    become_user: root
  - shell: . ~/.bashrc && pyenv install 3.8.1
      creates=~/.pyenv/versions/3.8.1/bin/python

  - file: path=~/deploy           state=directory
  - file: path=~/deploy/datastore state=directory
  - file: path=~/deploy/webui     state=directory

  - apt: name=libpq-dev state=present
    become: yes
    become_user: root
  - file: path=~/deploy/datastore/datastore-kredit state=directory
  - git:  >
      repo=git@gitlab.alto-apps.mine.nu:python/datastore-kredit.git
      dest=~/deploy/datastore/datastore-kredit/repo depth=1
      key_file=~/.ssh/ansible_testing
  - shell: . ~/.bashrc && pyenv virtualenv 3.8.1 kredit3.8
      creates=~/.pyenv/versions/kredit3.8/bin/python
  - pip: executable=~/.pyenv/versions/kredit3.8/bin/pip requirements=requirements.txt state=latest
      chdir=~/deploy/datastore/datastore-kredit/repo


- hosts: db
  become: yes
  tasks:
  - apt:     name=postgresql,python3-psycopg2 state=present
  - service: name=postgresql state=started enabled=yes

  - ufw: rule=allow port=5432 proto=tcp src=192.168.60.4
  - ufw: rule=allow port=5432 proto=tcp src=192.168.60.5

- hosts: db
  become: yes
  become_user: postgres
  tasks:
  - postgresql_user: name=alto password=alto
  - postgresql_db:   name=kredit owner=alto
