---
- block:
  - import_tasks: build.yml
  delegate_to: localhost
  run_once: True

- block:
  - import_tasks: deploy.yml
  become: yes
  become_user: "{{ deploy_user }}"

- block:
  - import_tasks: clean.yml
  delegate_to: localhost
  run_once: True
