---
- block:
  - apt: update_cache=yes cache_valid_time=3600
  - apt: name=tree,htop,net-tools state=present

  - apt:     name=ntp,openntpd state=absent
  - service: name=systemd-timesyncd state=started enabled=yes

  - ufw: rule=allow port=22 proto=tcp
  - ufw: state=enabled
  become: yes
