- block:
  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600
  - name: install packages
    apt: name=nginx,dirmngr,gnupg,apt-transport-https,ca-certificates,python3-apt state=present
  - name: add passenger gpg key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=561F9B9CAC40B2F7
  - name: add passenger repository
    apt_repository:
      filename: passenger
      repo: "deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main"
  - name: install passenger nginx module
    apt: name=libnginx-mod-http-passenger state=present
    notify: restart nginx

  - name: enable passenger module
    file:
      state: link
      src:  /usr/share/nginx/modules-available/mod-http-passenger.load
      dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    notify: restart nginx
  - name: define custom log format
    lineinfile:
      dest: /etc/nginx/nginx.conf
      line: "\tlog_format custom '[$time_local] $request_time $body_bytes_sent $remote_addr $status $request_method $host $request_uri';"
      regexp:      "^\\s*log_format\\s+custom\\s+"
      insertafter: "^\\s*error_log\\s+"
    notify: restart nginx
  - name: configure passenger
    lineinfile:
      dest: /etc/nginx/conf.d/mod-http-passenger.conf
      line:   "{{ item.line }}"
      regexp: "{{ item.regexp }}"
      create: yes
    with_items:
    - line:   "passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;"
      regexp: "^passenger_root\\s"
    - line:   "passenger_ruby /usr/bin/passenger_free_ruby;"
      regexp: "^passenger_ruby\\s"
    - line:   "passenger_log_file /var/log/nginx/passenger.log;"
      regexp: "^passenger_log_file\\s"
    notify: restart nginx

  - name: delete default vhost
    file:
      state: absent
      path:  /etc/nginx/sites-enabled/default
    notify: restart nginx
  - name: add http_to_https and vhost_not_found vhost configs
    copy: src={{ item }} dest=/etc/nginx/sites-available/
    with_items: ['0_http_to_https', '1_vhost_not_found', '2_status_page']
    notify: restart nginx
  - name: enable http_to_https and vhost_not_found vhosts
    file:
      state: link
      src:  /etc/nginx/sites-available/{{ item }}
      dest: /etc/nginx/sites-enabled/{{ item }}
    with_items: ['1_vhost_not_found', '2_status_page']
    # with_items: ['0_http_to_https', '1_vhost_not_found', '2_status_page']
    notify: restart nginx

  - name: allow HTTP and HTTPS access on firewall
    ufw: rule=allow port={{ item }} proto=tcp
    with_items: ["80", "443"]

  become: yes
