---
- block:
  - import_role: name=geerlingguy.postgresql
  - ufw: rule=allow proto=tcp src={{ item.address }} port={{ postgresql_port | string }}
    with_items: "{{ allowed_clients_eth1_ipv4 }}"
  become: yes
  vars:
    - allowed_clients_eth1_ipv4:
        "{{ allowed_clients | map('extract', hostvars, ['ansible_facts', 'eth1', 'ipv4']) | list }}"
    - postgresql_hba_entries:
        "{{ allowed_clients_eth1_ipv4 | map('ipv4_to_hba') | list | add_base_hba_entries }}"
    - postgresql_python_library: python3-psycopg2
    - postgresql_global_config_options: [{ option: listen_addresses, value: '*' }]
