---
- become: yes

  block:
  - name: set postgresql options
    set_fact:
      postgresql_global_config_options:
        "{{ postgresql_global_config_options + common_options + replication_master_options + replication_slave_options }}"
      postgresql_hba_entries:
        "{{ postgresql_hba_entries + replication_hba_entries }}"
      postgresql_users:
        - name: "{{ postgresql_replication_user }}"
          password: "{{ postgresql_replication_password }}"
          role_attr_flags: REPLICATION
  - import_role: name=geerlingguy.postgresql
  - name: allow connection from clients
    ufw: rule=allow proto=tcp src={{ item.address }} port={{ postgresql_port | string }}
    with_items: "{{ allowed_clients_ipv4 + replication_clients_ipv4 }}"

  vars:
    postgresql_iface_address:
      "{{ hostvars[inventory_hostname]['ansible_facts'][postgresql_iface]['ipv4']['address'] }}"
    postgresql_listen_addresses:
      "{{ (['127.0.0.1', postgresql_iface_address] + postgresql_additional_listen_addresses) | unique }}"

    allowed_clients_ipv4:
      "{{ postgresql_allowed_clients
        | difference([inventory_hostname])
        | map('extract', hostvars, ['ansible_facts', postgresql_iface, 'ipv4'])
        | list }}"
    postgresql_hba_entries:
      "{{ allowed_clients_ipv4
        | map('ipv4_to_hba')
        | list
        | add_base_hba_entries }}"

    replication_clients_ipv4:
      "{{ postgresql_replication_clients
        | difference([inventory_hostname])
        | map('extract', hostvars, ['ansible_facts', postgresql_iface, 'ipv4'])
        | list }}"
    accept_replication_hba_entries:
      "{{ replication_clients_ipv4
        | map('ipv4_to_hba', database = 'replication', user = postgresql_replication_user)
        | list
        | add_base_replication_hba_entries }}"
    reject_self_replication_hba_entry:
      "{{ ansible_facts[postgresql_iface]['ipv4']
        | ipv4_to_hba(database = 'replication', user = postgresql_replication_user, auth_method = 'reject') }}"
    replication_hba_entries:
      "{{ accept_replication_hba_entries + [reject_self_replication_hba_entry] }}"

    postgresql_python_library: python3-psycopg2

    common_options:
      - option: 'listen_addresses'
        value: "{{ postgresql_listen_addresses | join(',') }}"
      - option: 'logging_collector'
        value: 'off'
      - option: 'log_timezone'
        value: 'Europe/Prague'

    replication_master_options:
      - option: 'wal_level'
        value: 'replica'
      - option: 'archive_mode'
        value: 'off'
      # - option: 'archive_timeout'
      #   value:  "{{ postgresql_wal_timeout }}"
      # - option: 'archive_command'
      #   value: "test ! -f {{ postgresql_backups_dir }}/%f.gz && gzip < %p > {{ postgresql_backups_dir }}/%f.gz"

    replication_slave_options:
      - option: 'hot_standby'
        value: 'on'
      - option: 'hot_standby_feedback'
        value: 'on'
