postgresql_port: 5432
postgresql_wal_timeout: 300
postgresql_wal_keep_segments: 10
postgresql_replication_user: replicator
postgresql_additional_listen_addresses: []

postgresql_allowed_clients:
  "{{ groups.app | intersect(hosts_in_my_group) }}"
postgresql_replication_clients:
  "{{ groups.db | intersect(hosts_in_my_group) }}"
