postgresql_port: 5432
postgresql_version: 10
postgresql_cluster: main
postgresql_wal_timeout: 300
postgresql_replication_user: replicator
postgresql_additional_listen_addresses: []

postgresql_allowed_clients:
  "{{ groups.web + groups.apps | intersect(hosts_in_my_group) }}"
postgresql_replication_clients:
  "{{ groups.db | intersect(hosts_in_my_group) }}"
